{
 "title": "Gus",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {}
   },
   { "name": "filter", "query": "get" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Guía descriptiva de cada panel",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "options": {
      "content": "# Explicación de los paneles\n\nA continuación, se proporciona una breve explicación de cada uno de los paneles que figuran a continuación, en la pestaña “Log Details” . \n\n Estos paneles proporcionan visualizaciones interactivas que  permiten explorar y analizar los logs de manera eficiente. \n\n \n\nPanel 1: Gráfico de Pastel de Niveles de Log  por Porcentaje \n\nEste panel muestra un gráfico de pastel que distribuye los niveles de logs (como info, warning, debug, etc.) por porcentaje. Esta visualización permite obtener una visión rápida del tipo de eventos registrados en la aplicación. \n\nPanel 2: Distribución de Métodos HTTP Usados en un Intervalo de Tiempo \n\nEste panel muestra un gráfico de barras que visualiza la distribución de los métodos HTTP utilizados (GET, POST, DELETE, etc.) en un intervalo de tiempo que selecciona el usuario. \n\nPanel 3: Top 10 Rutas Más Utilizadas con Filtro Interactivo \n\nEste panel muestra las 10 rutas más utilizadas de la aplicación, con enlaces interactivos que permiten filtrar los logs por una ruta específica al hacer clic en un enlace. \n\nPanel 4: Tabla de Métodos, Niveles, Rutas y Cantidad \n\nEste panel muestra una tabla con cuatro columnas: Métodos HTTP, Nivel de Log, Ruta y Cantidad de Ocurrencias. Es útil para ver rápidamente la distribución de los logs por estos campos. \n\nPanel 5: Logs Más Recientes con Detalles Interactivos \n\nEste panel muestra los logs más recientes. Al hacer clic en un log, se pueden ver más detalles relacionados con ese log específico. "
     }
    }
   ]
  },
  {
   "title": "Log Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Levels Distribution",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 26 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(level) (count_over_time({app=\"web_app\"} |= `$filter` | json | level =~ `.+` [$__auto]))"
      }
     ]
    },
    {
     "title": "Methods Distribution",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 7, "x": 7, "y": 26 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(Method) (count_over_time({app=\"web_app\", service_name=\"$cluster\"} |= `$filter` | json | Method =~ `.+` [$__auto]))"
      }
     ]
    },
    {
     "title": "Top Ten Paths",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 10, "x": 14, "y": 26 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topK(10,sum by(Path) (count_over_time({app=\"web_app\", service_name=\"$cluster\"} |= `$filter` | json | Path =~ `.+` [$__auto])))"
      }
     ]
    },
    {
     "title": "Methods",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "topk(20, sum by(Method, level, Path) (count_over_time({app=\"web_app\", service_name=\"$cluster\"} |= `$filter` | json | Method =~ `.+` [$__auto])))"
      }
     ]
    },
    {
     "type": "logs",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "{app=\"web_app\", service_name=\"$cluster\"} |= `$filter` | json"
      }
     ]
    }
   ]
  }
 ]
}